version: "3.9"


services:
  db:
    image: postgres:15
    container_name: basic_task_db
    environment:
      POSTGRES_DB: basic_task_tracer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: basic_task_redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: basic_task_app
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basic_task_tracer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8089:8089"

volumes:
  pgdata:
