server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basic_task_tracer
    username: postgres
    password: sugarmommy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yml







